# Basic site settings
title: Mini LLM Flow
description: Minimalist LLM Framework in 100 Lines, Enabling LLMs to Program Themselves

# Theme settings
remote_theme: just-the-docs/just-the-docs

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "//github.com/zachary62/miniLLMFlow"

# Color scheme
color_scheme: light

mermaid:
  version: "9.1.3"  # Pick the version you want
  # Default configuration
  config: |
    directionLR